export const UserFormValidationConstants = {
  MIN_NAME_LENGTH: 1,
  MAX_NAME_LENGTH: 30,
  MIN_SURNAME_LENGTH: 1,
  MAX_SURNAME_LENGTH: 30,
  MIN_PHONE_NUMBER_LENGTH: 9,
  MAX_PHONE_NUMBER_LENGTH: 15,
  PESEL_LENGTH: 11,
  MIN_PASSWORD_LENGTH: 8,
  MAX_PASSWORD_LENGTH: 100,
};
